# Project: Healthcare Data Integration and Analysis
# - Hitesh Rathi - https://www.linkedin.com/in/hiteshrathi2001/

This template provides a starting point to help you complete the Tasks 3 and 4 of the project. The questions in this template are numbered in alignment with the Project Overview reading and submission template.
You can use it as-is, modify it, or create your own structure; just be sure to complete all the required tasks.

In [1]:
# Install required packages
import sqlite3
import requests
import pandas as pd
from pathlib import Path

# Task 3: Identify and fix the issues in a data set using Python

In [81]:
#load dataset
df = pd.read_csv("https://foundations-of-healthcare-data-analytics-4e579d.gitlab.io/labs/Projects/Patients_EHR_raw_data.csv")

In [82]:
#print top 5 rows
df.head()

  PatientID DateOfBirth  Gender  ZipCode        PrimaryCondition AdmissionDate
0     NV001  1983-03-11  Female  30933.0   Type 2 Diabetes (E11)    07-06-2024
1     NV004         NaN    Male  76999.0        Asthma (J45.909)    27-10-2022
2     NV005  1984-08-25  Female  40307.0  Osteoarthritis (M15.9)    30-10-2024
3     NV006  1982-12-16  Female  56844.0   Type 2 Diabetes (E11)    05-07-2022
4     NV007  1990-10-11    Male      NaN  Hyperlipidemia (E78.5)    17-06-2024

### 3.1a. Write the Python code to identify the Number of missing values.

In [83]:
# Missing values by column
missing_values = df.isnull().sum()

print("Missing values by column:")
print(missing_values)

print("\nTotal missing values in dataset:")
print(df.isnull().sum().sum())

Missing values by column:
PatientID           0
DateOfBirth         3
Gender              0
ZipCode             4
PrimaryCondition    0
AdmissionDate       0
dtype: int64

Total missing values in dataset:
7

### 3.1b. Write the Python code to identify the number of duplicate rows.

In [84]:
# Count duplicate rows
duplicate_rows = df.duplicated().sum()

print("Number of duplicate rows:")
print(duplicate_rows)

# Display duplicate rows if any
df[df.duplicated(keep=False)]

Number of duplicate rows:
2

   PatientID DateOfBirth Gender  ZipCode        PrimaryCondition AdmissionDate
20     NV028  18-05-1978   Male      NaN   Type 2 Diabetes (E11)    27-10-2022
21     NV028  18-05-1978   Male      NaN   Type 2 Diabetes (E11)    27-10-2022
43     NV053  1941-04-03   Male  39856.0  Hyperlipidemia (E78.5)    17-06-2024
44     NV053  1941-04-03   Male  39856.0  Hyperlipidemia (E78.5)    17-06-2024

### 3.1c Write the Python code to identify inconsistent categorical entries in the Gender column.

In [85]:
# Check all unique values in Gender column
print("Unique values in Gender column:")
print(df["Gender"].unique())

# Count each Gender entry
print("\nGender value counts:")
print(df["Gender"].value_counts(dropna=False))

Unique values in Gender column:
['Female' 'Male' 'M' 'male' 'F']

Gender value counts:
Gender
Female    34
Male      34
F          4
M          1
male       1
Name: count, dtype: int64

### 3.1d Write the Python code to identify inconsistent date formats in the AdmissionDate column.

In [86]:
# View unique AdmissionDate values
print("Sample AdmissionDate values:")
print(df["AdmissionDate"].head(20))

# Try converting AdmissionDate to datetime
converted_dates = pd.to_datetime(df["AdmissionDate"], errors="coerce", infer_datetime_format=True)

# Count dates that could not be converted
invalid_dates = converted_dates.isnull().sum()

print("Number of inconsistent or invalid AdmissionDate values:")
print(invalid_dates)

# Display rows with invalid AdmissionDate values
df[converted_dates.isnull()]

Sample AdmissionDate values:
0     07-06-2024
1     27-10-2022
2     30-10-2024
3     05-07-2022
4     17-06-2024
5          45258
6     09-05-2024
7     25-06-2023
8     21-09-2024
9     07-07-2022
10    23-05-2023
11    16-07-2023
12    19-03-2022
13    03-04-2024
14    14-11-2024
15    25-06-2024
16    21-03-2024
17    18-10-2022
18    17-09-2022
19    30-10-2024
Name: AdmissionDate, dtype: object
Number of inconsistent or invalid AdmissionDate values:
42

/tmp/ipykernel_5297/4132336500.py:6: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  converted_dates = pd.to_datetime(df["AdmissionDate"], errors="coerce", infer_datetime_format=True)

,PatientID,DateOfBirth,Gender,ZipCode,PrimaryCondition,AdmissionDate
1,NV004,NaN,Male,76999.0,Asthma (J45.909),27-10-2022
2,NV005,1984-08-25,Female,40307.0,Osteoarthritis (M15.9),30-10-2024
4,NV007,1990-10-11,Male,NaN,Hyperlipidemia (E78.5),17-06-2024
5,NV008,1949-07-08,Male,56844.0,Hyperlipidemia (E78.5),45258
7,NV010,1944-11-11,Female,41617.0,Osteoarthritis (M15.9),25-06-2023
8,NV012,1975-01-14,Female,33023.0,Hypertension (I10),21-09-2024
10,NV015,1959-11-20,M,45116.0,Hypertension (I10),23-05-2023
11,NV017,1970-07-06,Female,67793.0,Hyperlipidemia (E78.5),16-07-2023
12,NV019,1944-08-03,Female,40307.0,Asthma (J45.909),19-03-2022
14,NV022,1957-01-02,Female,45989.0,Hypertension (I10),14-11-2024
15,NV023,1974-05-18,Male,62729.0,Osteoarthritis (M15.9),25-06-2024
16,NV024,1958-08-13,Female,19045.0,Type 2 Diabetes (E11),21-03-2024
17,NV025,1972-05-02,Female,54291.0,Type 2 Diabetes (E11),18-10-2022
18,NV026,1975-04-09,Female,99104.0,Type 2 Diabetes (E11),17-09-2022
19,NV027,1997-12-28,Male,70714.0,Asthma (J45.909),30-10-2024
20,NV028,18-05-1978,Male,NaN,Type 2 Diabetes (E11),27-10-2022
21,NV028,18-05-1978,Male,NaN,Type 2 Diabetes (E11),27-10-2022
22,NV029,1976-08-31,Female,41617.0,Asthma (J45.909),21-05-2022
26,NV033,1951-02-03,Female,10156.0,Hypertension (I10),18-02-2023
27,NV034,1974-05-18,Female,14441.0,Type 2 Diabetes (E11),16-08-2023
30,NV038,1965-03-12,Male,86850.0,Type 2 Diabetes (E11),16-04-2024
32,NV041,1999-03-01,Male,71435.0,Hypertension (I10),17-11-2023
35,NV046,1949-07-07,Male,26372.0,Asthma (J45.909),27-05-2024
36,NV046,1944-06-23,Male,84333.0,Asthma (J45.909),20-04-2024
37,NV046,1949-07-07,Male,26372.0,Asthma (J45.909),45439.00
38,NV047,1945-03-08,Male,84393.0,Hypertension (I10),21-10-2022
39,NV049,1958-07-23,Male,25152.0,Osteoarthritis (M15.9),23-08-2022
40,NV050,1978-01-20,Female,13411.0,Asthma (J45.909),15-11-2023
41,NV051,1971-08-06,Female,29205.0,Type 2 Diabetes (E11),18-04-2022
43,NV053,1941-04-03,Male,39856.0,Hyperlipidemia (E78.5),17-06-2024
44,NV053,1941-04-03,Male,39856.0,Hyperlipidemia (E78.5),17-06-2024
45,NV054,1992-05-27,Male,47285.0,Hypertension (I10),16-07-2024
47,NV059,NaN,Female,53017.0,UNKNOWN,15-12-2023
53,NV070,1951-02-03,F,17401.0,Type 2 Diabetes (E11),15-08-2022
54,NV072,1992-11-01,Female,12050.0,Type 2 Diabetes (E11),20-09-2023
55,NV073,1959-05-21,Male,87372.0,Hypertension (I10),24-04-2023
60,NV079,1984-06-03,Female,47672.0,Asthma (J45.909),13-05-2023
61,NV081,1977-10-22,Male,63889.0,Type 2 Diabetes (E11),20-11-2023
65,NV086,1997-11-18,Male,12201.0,Osteoarthritis (M15.9),24-08-2023
70,NV093,1995-10-18,F,38743.0,Hyperlipidemia (E78.5),18-05-2022
72,NV096,1972-01-04,Male,61408.0,Type 2 Diabetes (E11),18-02-2023
73,NV098,1981-06-13,Male,29205.0,Hyperlipidemia (E78.5),17-12-2023

### 3.2a Write the Python code to handle missing values appropriately.

In [87]:
# 3.2a Handle missing values appropriately

# Fill missing DateOfBirth values with 'Unknown'
df["DateOfBirth"] = df["DateOfBirth"].fillna("Unknown")

# Fill missing ZipCode values with 'Unknown'
df["ZipCode"] = df["ZipCode"].fillna("Unknown")

# Check missing values after handling
print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
PatientID           0
DateOfBirth         0
Gender              0
ZipCode             0
PrimaryCondition    0
AdmissionDate       0
dtype: int64

### 3.2b Write the Python code to remove exact duplicate rows.

In [88]:
# 3.2b Identify and remove exact duplicate rows, keeping only the first occurrence

# Count duplicate rows before cleaning
print("Number of duplicate rows before cleaning:")
print(df.duplicated().sum())

# Display all duplicate records, including the first occurrence
duplicate_records = df[df.duplicated(keep=False)]

print("\nDuplicate records:")
display(duplicate_records)

# Remove exact duplicate rows, keeping only the first occurrence
df = df.drop_duplicates(keep="first")

# Check duplicates after removal
print("\nNumber of duplicate rows after cleaning:")
print(df.duplicated().sum())

Number of duplicate rows before cleaning:
2

Duplicate records:

   PatientID DateOfBirth Gender  ZipCode        PrimaryCondition AdmissionDate
20     NV028  18-05-1978   Male  Unknown   Type 2 Diabetes (E11)    27-10-2022
21     NV028  18-05-1978   Male  Unknown   Type 2 Diabetes (E11)    27-10-2022
43     NV053  1941-04-03   Male  39856.0  Hyperlipidemia (E78.5)    17-06-2024
44     NV053  1941-04-03   Male  39856.0  Hyperlipidemia (E78.5)    17-06-2024

Number of duplicate rows after cleaning:
0

### 3.2c Write the Python code to standardize gender values.

In [89]:
# 3.2c Standardize Gender values

df["Gender"] = df["Gender"].astype(str).str.strip().str.lower()

df["Gender"] = df["Gender"].replace({
    "m": "Male",
    "male": "Male",
    "f": "Female",
    "female": "Female"
})

# Check Gender values after standardisation
print("Gender values after standardisation:")
print(df["Gender"].value_counts())

Gender values after standardisation:
Gender
Female    38
Male      34
Name: count, dtype: int64

### 3.2d Write the Python code to standardize date values.

In [90]:
# 3.2d Standardize AdmissionDate values without creating an original column

# Clean AdmissionDate as text
date_col = df["AdmissionDate"].astype(str).str.strip()

# Convert possible Excel serial dates to numeric
numeric_dates = pd.to_numeric(date_col, errors="coerce")

# Identify Excel serial dates such as 45258 or 45439
is_excel_serial = numeric_dates.notna()

# Create empty datetime series
standardized_dates = pd.Series(pd.NaT, index=df.index)

# Convert Excel serial dates
standardized_dates.loc[is_excel_serial] = pd.to_datetime(
    numeric_dates.loc[is_excel_serial],
    unit="D",
    origin="1899-12-30",
    errors="coerce"
)

# Convert normal date strings, e.g. 07-06-2024
standardized_dates.loc[~is_excel_serial] = pd.to_datetime(
    date_col.loc[~is_excel_serial],
    dayfirst=True,
    errors="coerce"
)

# Save standardized dates back to AdmissionDate
df["AdmissionDate"] = standardized_dates.dt.strftime("%Y-%m-%d")

# Check results
print("AdmissionDate after standardisation:")
print(df[["PatientID", "AdmissionDate"]].head(20))

print("\nInvalid or missing AdmissionDate values after conversion:")
print(df["AdmissionDate"].isnull().sum())

AdmissionDate after standardisation:
   PatientID AdmissionDate
0      NV001    2024-06-07
1      NV004    2022-10-27
2      NV005    2024-10-30
3      NV006    2022-07-05
4      NV007    2024-06-17
5      NV008    2023-11-28
6      NV009    2024-05-09
7      NV010    2023-06-25
8      NV012    2024-09-21
9      NV014    2022-07-07
10     NV015    2023-05-23
11     NV017    2023-07-16
12     NV019    2022-03-19
13     NV020    2024-04-03
14     NV022    2024-11-14
15     NV023    2024-06-25
16     NV024    2024-03-21
17     NV025    2022-10-18
18     NV026    2022-09-17
19     NV027    2024-10-30

Invalid or missing AdmissionDate values after conversion:
0

In [94]:
# Check duplicate rows again

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:")
print(duplicate_count)

# Display duplicate records if any
duplicate_records = df[df.duplicated(keep=False)]

print("\nDuplicate records:")
display(duplicate_records)

Number of duplicate rows:
0

Duplicate records:

Empty DataFrame
Columns: [PatientID, DateOfBirth, Gender, ZipCode, PrimaryCondition, AdmissionDate]
Index: []

# Task 4: Analyze the data sets using SQL

## Medical Data SQLite Exploration
Before you write the queries listed in Task 4 of the project, execute the cells in this section to inspect table structure and query sample rows.

In [95]:
db_url = "https://foundations-of-healthcare-data-analytics-4e579d.gitlab.io/labs/medical_data.db"  # replace
db_path = Path("medical_data.db")

In [96]:
response = requests.get(db_url)
response.raise_for_status()
db_path.write_bytes(response.content)
print("Downloaded to", db_path)

Downloaded to medical_data.db

In [97]:
conn = sqlite3.connect(db_path)
cur = conn.cursor()

In [98]:
def run_query(query: str):
    df = pd.read_sql_query(query, conn)
    display(df)

### Table structure: pharmacy_claims

In [99]:
run_query("PRAGMA table_info(pharmacy_claims);")

   cid          name       type  notnull dflt_value  pk
0    0       ClaimID       TEXT        0       None   0
1    1     PatientID       TEXT        0       None   0
2    2    Medication       TEXT        0       None   0
3    3        Dosage       TEXT        0       None   0
4    4      FillDate  TIMESTAMP        0       None   0
5    5         Payer       TEXT        0       None   0
6    6      ClinicID       TEXT        0       None   0
7    7  ChargeAmount       REAL        0       None   0
8    8    PaidAmount       REAL        0       None   0

### Table structure: lab_results

In [100]:
run_query("PRAGMA table_info(lab_results);")

   cid                name       type  notnull dflt_value  pk
0    0           PatientID       TEXT        0       None   0
1    1           LabTestID       TEXT        0       None   0
2    2      CollectionDate  TIMESTAMP        0       None   0
3    3            TestName       TEXT        0       None   0
4    4     TestResultValue       REAL        0       None   0
5    5               Units       TEXT        0       None   0
6    6   ReferenceRangeLow       REAL        0       None   0
7    7  ReferenceRangeHigh       REAL        0       None   0
8    8        AbnormalFlag       TEXT        0       None   0

### Table structure: patients

In [101]:
run_query("PRAGMA table_info(patients);")

   cid              name       type  notnull dflt_value  pk
0    0         PatientID       TEXT        0       None   0
1    1       DateOfBirth  TIMESTAMP        0       None   0
2    2            Gender       TEXT        0       None   0
3    3           ZipCode    INTEGER        0       None   0
4    4  PrimaryCondition       TEXT        0       None   0
5    5     AdmissionDate  TIMESTAMP        0       None   0

### Top 5 patients

In [102]:
run_query("SELECT * FROM patients LIMIT 5;")

,PatientID,DateOfBirth,Gender,ZipCode,PrimaryCondition,AdmissionDate
0,NV094,1962-11-05 00:00:00,Female,95982,Osteoarthritis (M15.9),2023-11-06 00:00:00
1,NV027,1997-12-28 00:00:00,Male,70714,Asthma (J45.909),2024-10-30 00:00:00
2,NV005,1984-08-25 00:00:00,Female,40307,Osteoarthritis (M15.9),2024-10-30 00:00:00
3,NV031,1976-07-08 00:00:00,Female,26647,Asthma (J45.909),2024-08-07 00:00:00
4,NV008,1949-07-08 00:00:00,Male,56844,Hyperlipidemia (E78.5),2023-11-28 00:00:00

## Write the SQL queries and execute them.
The questions are numbered in alignment with the Project Overview reading and submission template.

### 4.1a Write an SQL query to list all patients born before 1980.

In [105]:
run_query("""
SELECT *
FROM patients
WHERE DATE(DateOfBirth) < '1980-01-01';
""")

,PatientID,DateOfBirth,Gender,ZipCode,PrimaryCondition,AdmissionDate
0,NV094,1962-11-05 00:00:00,Female,95982,Osteoarthritis (M15.9),2023-11-06 00:00:00
1,NV031,1976-07-08 00:00:00,Female,26647,Asthma (J45.909),2024-08-07 00:00:00
2,NV008,1949-07-08 00:00:00,Male,56844,Hyperlipidemia (E78.5),2023-11-28 00:00:00
3,NV046,1949-07-07 00:00:00,Male,26372,Asthma (J45.909),2024-05-27 00:00:00
4,NV089,1943-07-18 00:00:00,Female,87372,Osteoarthritis (M15.9),2024-01-12 00:00:00
5,NV029,1976-08-31 00:00:00,Female,41617,Asthma (J45.909),2022-05-21 00:00:00
6,NV017,1961-07-27 00:00:00,Male,14441,Hyperlipidemia (E78.5),2022-02-12 00:00:00
7,NV012,1966-07-24 00:00:00,Male,67468,Hypertension (I10),2023-12-07 00:00:00
8,NV010,1947-11-12 00:00:00,Female,10156,Osteoarthritis (M15.9),2023-05-13 00:00:00
9,NV076,1956-02-09 00:00:00,Female,14863,Asthma (J45.909),2024-02-27 00:00:00
10,NV036,1976-12-16 00:00:00,Male,76999,Type 2 Diabetes (E11),2022-11-28 00:00:00
11,NV063,1977-10-18 00:00:00,Female,44034,Asthma (J45.909),2022-09-02 00:00:00
12,NV080,1957-04-09 00:00:00,Male,54291,Hyperlipidemia (E78.5),2023-02-22 00:00:00
13,NV048,1974-06-21 00:00:00,Male,84333,Type 2 Diabetes (E11),2023-08-27 00:00:00
14,NV098,1961-06-18 00:00:00,Female,42801,Osteoarthritis (M15.9),2024-06-08 00:00:00
15,NV058,1971-08-01 00:00:00,Female,47285,Asthma (J45.909),2023-04-29 00:00:00
16,NV077,1958-01-20 00:00:00,Male,33292,Hypertension (I10),2024-10-09 00:00:00
17,NV084,1942-03-24 00:00:00,Female,13411,Hyperlipidemia (E78.5),2023-11-15 00:00:00
18,NV099,1951-11-29 00:00:00,Male,62729,Type 2 Diabetes (E11),2024-07-25 00:00:00
19,NV085,1963-04-26 00:00:00,Female,20377,Asthma (J45.909),2024-10-15 00:00:00
20,NV091,1955-08-04 00:00:00,Male,86850,Hyperlipidemia (E78.5),2024-08-20 00:00:00
21,NV009,1970-06-13 00:00:00,Male,47672,Hyperlipidemia (E78.5),2024-06-25 00:00:00
22,NV054,1960-06-25 00:00:00,Female,37525,Hypertension (I10),2024-03-08 00:00:00
23,NV023,1958-06-17 00:00:00,Female,85023,Osteoarthritis (M15.9),2023-10-17 00:00:00
24,NV021,1978-08-14 00:00:00,Female,33023,Hypertension (I10),2023-06-23 00:00:00
25,NV024,1952-09-09 00:00:00,Male,29205,Type 2 Diabetes (E11),2022-08-11 00:00:00
26,NV081,1968-12-19 00:00:00,Female,19045,Type 2 Diabetes (E11),2024-03-25 00:00:00
27,NV053,1979-05-06 00:00:00,Male,63889,Hyperlipidemia (E78.5),2024-03-10 00:00:00
28,NV047,1951-03-02 00:00:00,Male,85942,Hypertension (I10),2023-06-11 00:00:00
29,NV052,1975-01-14 00:00:00,Female,70498,Osteoarthritis (M15.9),2024-09-21 00:00:00
30,NV086,1971-08-06 00:00:00,Female,54160,Type 2 Diabetes (E11),2022-04-18 00:00:00
31,NV073,1958-08-13 00:00:00,Female,66579,Hypertension (I10),2024-03-21 00:00:00
32,NV038,1977-10-22 00:00:00,Male,67793,Type 2 Diabetes (E11),2023-11-20 00:00:00
33,NV049,1950-12-16 00:00:00,Female,38743,Asthma (J45.909),2022-03-05 00:00:00
34,NV007,1968-04-03 00:00:00,Female,69986,Osteoarthritis (M15.9),2022-10-04 00:00:00
35,NV014,1963-07-23 00:00:00,Male,27602,Hyperlipidemia (E78.5),2023-08-01 00:00:00
36,NV096,1970-07-06 00:00:00,Female,34187,Hypertension (I10),2023-07-16 00:00:00
37,NV019,1972-04-17 00:00:00,Male,14272,Asthma (J45.909),2023-01-08 00:00:00
38,NV062,1957-01-02 00:00:00,Female,37775,Type 2 Diabetes (E11),2024-11-14 00:00:00
39,NV006,1945-03-08 00:00:00,Male,45802,Type 2 Diabetes (E11),2022-10-21 00:00:00
40,NV035,1975-04-09 00:00:00,Female,45989,Hyperlipidemia (E78.5),2022-09-17 00:00:00
41,NV013,1955-07-11 00:00:00,Female,84393,Hypertension (I10),2024-05-09 00:00:00
42,NV079,1965-03-12 00:00:00,Female,99104,Asthma (J45.909),2022-07-07 00:00:00
43,NV059,1959-11-20 00:00:00,Male,67667,Type 2 Diabetes (E11),2023-05-23 00:00:00
44,NV004,1959-05-27 00:00:00,Female,99195,Asthma (J45.909),2023-03-11 00:00:00
45,NV075,1944-08-03 00:00:00,Female,45116,Hypertension (I10),2022-03-19 00:00:00

### 4.1b Write an SQL query to list all female patients with Type 2 Diabetes.

In [106]:
run_query("""
SELECT
   *
FROM patients
WHERE Gender = 'Female'
  AND PrimaryCondition LIKE '%Type 2 Diabetes%';
""")

,PatientID,DateOfBirth,Gender,ZipCode,PrimaryCondition,AdmissionDate
0,NV072,1992-11-01 00:00:00,Female,12050,Type 2 Diabetes (E11),2023-09-20 00:00:00
1,NV001,1983-03-11 00:00:00,Female,30933,Type 2 Diabetes (E11),2024-06-07 00:00:00
2,NV061,1986-07-06 00:00:00,Female,48060,Type 2 Diabetes (E11),2024-04-20 00:00:00
3,NV081,1968-12-19 00:00:00,Female,19045,Type 2 Diabetes (E11),2024-03-25 00:00:00
4,NV086,1971-08-06 00:00:00,Female,54160,Type 2 Diabetes (E11),2022-04-18 00:00:00
5,NV062,1957-01-02 00:00:00,Female,37775,Type 2 Diabetes (E11),2024-11-14 00:00:00

### 4.1c Write an SQL query to display all lab tests performed. List each patient (PatientID, Gender, and DateOfBirth from *patients*) with their Lab test name and result value (TestName and TestResultValue from *lab_results*).

In [107]:
run_query("""
SELECT
    p.PatientID,
    p.Gender,
    p.DateOfBirth,
    l.TestName,
    l.TestResultValue
FROM patients p
JOIN lab_results l
    ON p.PatientID = l.PatientID;
""")

    PatientID  Gender          DateOfBirth         TestName  TestResultValue
0       NV094  Female  1962-11-05 00:00:00       Creatinine             1.22
1       NV094  Female  1962-11-05 00:00:00            HbA1c             7.83
2       NV094  Female  1962-11-05 00:00:00            HbA1c             9.22
3       NV027    Male  1997-12-28 00:00:00            HbA1c             4.13
4       NV027    Male  1997-12-28 00:00:00            HbA1c             7.24
..        ...     ...                  ...              ...              ...
196     NV065    Male  1984-09-09 00:00:00            HbA1c             5.56
197     NV065    Male  1984-09-09 00:00:00  LDL Cholesterol           102.72
198     NV075  Female  1944-08-03 00:00:00       Creatinine             0.92
199     NV075  Female  1944-08-03 00:00:00            HbA1c             4.02
200     NV075  Female  1944-08-03 00:00:00            HbA1c             5.32

[201 rows x 5 columns]

### 4.1d Write an SQL query to display all distinct patients with their payer(s). List each patient (PatientID, Gender, and DateofBirth from *patients*) with their payer(s) from *pharmacy_claims*).

In [108]:
run_query("""
SELECT DISTINCT
    p.PatientID,
    p.Gender,
    p.DateOfBirth,
    pc.Payer
FROM patients p
JOIN pharmacy_claims pc
    ON p.PatientID = pc.PatientID;
""")

   PatientID  Gender          DateOfBirth     Payer
0      NV094  Female  1962-11-05 00:00:00  Medicare
1      NV027    Male  1997-12-28 00:00:00  Medicaid
2      NV005  Female  1984-08-25 00:00:00  Medicaid
3      NV031  Female  1976-07-08 00:00:00   Private
4      NV008    Male  1949-07-08 00:00:00  Medicare
5      NV046    Male  1949-07-07 00:00:00  Medicaid
6      NV089  Female  1943-07-18 00:00:00  Medicare
7      NV072  Female  1992-11-01 00:00:00   Private
8      NV029  Female  1976-08-31 00:00:00  Medicaid
9      NV001  Female  1983-03-11 00:00:00  Medicaid
10     NV017    Male  1961-07-27 00:00:00  Medicare
11     NV012    Male  1966-07-24 00:00:00  Medicaid
12     NV010  Female  1947-11-12 00:00:00  Medicare
13     NV076  Female  1956-02-09 00:00:00   Private
14     NV043    Male  1980-04-10 00:00:00   Private
15     NV036    Male  1976-12-16 00:00:00  Medicare
16     NV063  Female  1977-10-18 00:00:00  Medicare
17     NV080    Male  1957-04-09 00:00:00  Medicaid
18     NV048    Male  1974-06-21 00:00:00   Private
19     NV039    Male  1981-08-07 00:00:00   Private
20     NV061  Female  1986-07-06 00:00:00  Medicare
21     NV071    Male  1986-10-06 00:00:00  Medicare
22     NV098  Female  1961-06-18 00:00:00  Medicaid
23     NV058  Female  1971-08-01 00:00:00   Private
24     NV077    Male  1958-01-20 00:00:00   Private
25     NV084  Female  1942-03-24 00:00:00  Medicare
26     NV025    Male  1989-10-01 00:00:00   Private
27     NV099    Male  1951-11-29 00:00:00  Medicaid
28     NV085  Female  1963-04-26 00:00:00   Private
29     NV091    Male  1955-08-04 00:00:00  Medicaid
30     NV009    Male  1970-06-13 00:00:00  Medicare
31     NV054  Female  1960-06-25 00:00:00   Private
32     NV023  Female  1958-06-17 00:00:00   Private
33     NV090    Male  1980-08-26 00:00:00  Medicaid
34     NV021  Female  1978-08-14 00:00:00   Private
35     NV024    Male  1952-09-09 00:00:00  Medicaid
36     NV081  Female  1968-12-19 00:00:00   Private
37     NV053    Male  1979-05-06 00:00:00  Medicare
38     NV047    Male  1951-03-02 00:00:00  Medicaid
39     NV052  Female  1975-01-14 00:00:00  Medicare
40     NV086  Female  1971-08-06 00:00:00   Private
41     NV073  Female  1958-08-13 00:00:00  Medicare
42     NV038    Male  1977-10-22 00:00:00  Medicare
43     NV049  Female  1950-12-16 00:00:00  Medicare
44     NV015    Male  1984-06-16 00:00:00  Medicare
45     NV007  Female  1968-04-03 00:00:00   Private
46     NV014    Male  1963-07-23 00:00:00   Private
47     NV096  Female  1970-07-06 00:00:00  Medicaid
48     NV093  Female  1995-10-18 00:00:00  Medicaid
49     NV019    Male  1972-04-17 00:00:00  Medicare
50     NV062  Female  1957-01-02 00:00:00   Private
51     NV006    Male  1945-03-08 00:00:00   Private
52     NV035  Female  1975-04-09 00:00:00   Private
53     NV013  Female  1955-07-11 00:00:00  Medicaid
54     NV079  Female  1965-03-12 00:00:00   Private
55     NV088    Male  1983-09-18 00:00:00  Medicare
56     NV059    Male  1959-11-20 00:00:00  Medicare
57     NV004  Female  1959-05-27 00:00:00   Private
58     NV065    Male  1984-09-09 00:00:00  Medicaid
59     NV075  Female  1944-08-03 00:00:00  Medicaid